services:
  pairdrop:
    image: 'lscr.io/linuxserver/pairdrop:latest'
    container_name: 'pairdrop'
    ports:
      - '3000:3000'
    environment:
      - PUID=1000 # UID to run the application as
      - PGID=1000 # GID to run the application as
      - WS_FALLBACK=true # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
      - RTC_CONFIG=false # Set to the path of a file that specifies the STUN/TURN servers.
      - DEBUG_MODE=false # Set to true to debug container and peer connections.
      - TZ=Asia/Kolkata
    restart: unless-stopped
