version: '3.8'
# Default admin credentials: username - admin, password - admin123

services:
  clipcascade:
    image: sathvikrao/clipcascade:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      # To learn more about environment variables, check the Advanced Details section in the GitHub README.
      - CC_MAX_MESSAGE_SIZE_IN_MiB=1
      # - CC_ALLOWED_ORIGINS=https://clipcascade.example.com
      # - CC_SERVER_DB_PASSWORD=QjuGlhE3uwylBBANMkX1 o2MdEoFgbU5XkFvTftky
      # - CC_SERVER_LOGGING_LEVEL=DEBUG
    volumes:
      - ./cc_users:/database
#external caddy auto handles SSL certs
#this is for arm64 ONLY
