version: "3"
services:
    trilium:
        ports:
            - 8080:8080
        volumes:
            - ./trilium-data:/home/node/trilium-data
        image: triliumnext/notes:stable
#        command: "%%{WARNING}%%"
# external caddy handles SSl certs
