version: "3.8"

services:
  ergo:
    init: true
    image: ghcr.io/ergochat/ergo:stable
    ports:
      - "6668:6667/tcp"
      - "6698:6697/tcp"
    volumes:
      - ./data:/ircd
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
      replicas: 1

volumes:
  data:
