version: '3.3'
services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    # Replace my paths (prior to the colons) with your own
    volumes:
      - ./config:/config
      - /path/to/library:/data:ro
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
# external caddy handles SSL certs
