version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
    - '80:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
# external caddy handles SSL certs
